#!/usr/bin/env python3
"""Generate exact normalized Gegenbauer reference data for R008."""
from __future__ import annotations
from fractions import Fraction as Q
from hashlib import sha256
from pathlib import Path
import json
from generate_bernstein_certificates import normalized_gegenbauer, qobj, lean_q
ROOT=Path(__file__).resolve().parent; PROJECT_ROOT=ROOT.parent; LEAN_ROOT=PROJECT_ROOT/"lean-overlay" if (PROJECT_ROOT/"lean-overlay").is_dir() else PROJECT_ROOT
OUT_JSON=ROOT/"gegenbauer_reference.json"; OUT_LEAN=LEAN_ROOT/"R008"/"Generated"/"GegenbauerData.lean"; OUT_SUMMARY=ROOT/"gegenbauer_reference_summary.json"
USED={5:[0,1,2,3,4,9],4:[0,1,2,3,6]}
def qtext(q): return str(q.numerator) if q.denominator==1 else f"{q.numerator}/{q.denominator}"
def lean_list(values): return "[\n    "+",\n    ".join(lean_q(x) for x in values)+"\n  ]"
def ident(d,k): return f"d{d}k{k}"
def main():
    data={"normalization":"P_k^(d)(1)=1","ambientDimensions":{}}; records=[]
    for d,degrees in USED.items():
        entries=[]
        for k in degrees:
            coefficients=normalized_gegenbauer(k,d); assert sum(coefficients)==1; entries.append({"degree":k,"powerCoefficientsAscending":[qobj(q) for q in coefficients]}); records.append((d,k,coefficients))
        data["ambientDimensions"][str(d)]=entries
    text=json.dumps(data,indent=2,sort_keys=True)+"\n"; OUT_JSON.write_text(text,encoding="utf-8"); digest=sha256(text.encode()).hexdigest()
    lines=["import Mathlib.Data.Rat.Defs","","/-!","# Generated exact normalized Gegenbauer reference data for R008","","Generated by `certificates/generate_gegenbauer_reference.py`.","These are exact power-basis targets.  The recurrence-to-reference","equalities must be proved in Lean; this data file alone is not that proof.","-/","","set_option autoImplicit false","","namespace R008.Generated.GegenbauerReference",""]
    for d,k,coefficients in records: lines += [f"/-- Normalized degree-{k} Gegenbauer polynomial for ambient dimension {d}. -/",f"def {ident(d,k)} : List ℚ := {lean_list(coefficients)}",""]
    lines.append("def all : List (Nat × Nat × List ℚ) := [")
    for index,(d,k,_) in enumerate(records): lines.append(f"  ({d}, {k}, {ident(d,k)}){',' if index+1<len(records) else ''}")
    lines += ["]","","end R008.Generated.GegenbauerReference",""]; OUT_LEAN.parent.mkdir(parents=True,exist_ok=True); OUT_LEAN.write_text("\n".join(lines),encoding="utf-8")
    summary={"referenceSha256":digest,"polynomialCount":len(records),"usedDegrees":{str(d):degrees for d,degrees in USED.items()},"coefficients":{ident(d,k):[qtext(q) for q in coefficients] for d,k,coefficients in records}}; OUT_SUMMARY.write_text(json.dumps(summary,indent=2,sort_keys=True)+"\n",encoding="utf-8"); print(f"R008 Gegenbauer reference generated: {len(records)} polynomials"); print(f"reference sha256: {digest}")
if __name__=="__main__": main()
