#!/usr/bin/env python3
"""Generate Lean proof instances for all exact R008 Bernstein pieces.

The generated identities are intended to be checked by Lean's `ring_nf` tactic
after exact reduction of the finite Bernstein expansion. The Python process
supplies data and proof scripts but is not part of the final proof oracle.
"""
from __future__ import annotations
from fractions import Fraction as Q
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = ROOT.parent
LEAN_ROOT = PROJECT_ROOT / "lean-overlay" if (PROJECT_ROOT / "lean-overlay").is_dir() else PROJECT_ROOT
DOC = json.loads((ROOT / "bernstein_certificates.json").read_text())
OUT = LEAN_ROOT / "R008" / "Generated" / "BernsteinProofs.lean"


def q(o: dict) -> Q:
    return Q(o["numerator"], o["denominator"])


def lean_r(x: Q) -> str:
    if x.denominator == 1:
        return f"(-({-x.numerator} : ℝ))" if x.numerator < 0 else f"({x.numerator} : ℝ)"
    return (
        f"(-({-x.numerator} : ℝ)) / {x.denominator}"
        if x.numerator < 0
        else f"({x.numerator} : ℝ) / {x.denominator}"
    )


def polynomial_expr(coeffs: list[Q], variable: str = "t") -> str:
    terms: list[str] = []
    for i, c in enumerate(coeffs):
        if c == 0:
            continue
        cc = lean_r(c)
        if i == 0:
            terms.append(cc)
        elif i == 1:
            terms.append(f"({cc}) * {variable}")
        else:
            terms.append(f"({cc}) * {variable} ^ {i}")
    return " +\n    ".join(terms) if terms else "0"


def vector_expr(values: list[Q]) -> str:
    return "![\n    " + ",\n    ".join(lean_r(x) for x in values) + "\n  ]"


def ident(name: str) -> str:
    return name


def generate() -> str:
    lines: list[str] = [
        "import R008.Bernstein",
        "import R008.Interval",
        "import Mathlib.Data.Fin.VecNotation",
        "import Mathlib.Tactic",
        "",
        "/-!",
        "# Generated Lean instances for the R008 Bernstein certificates",
        "",
        "Generated by `certificates/generate_lean_certificate_proofs.py` from",
        "the exact JSON certificate. Every affine polynomial identity is",
        "reproved by Lean's exact normalization and `ring_nf`; every coefficient",
        "bound is closed by exact normalization. This file contains no `sorry`,",
        "no axiom, and no native decision proof.",
        "-/",
        "",
        "set_option autoImplicit false",
        "set_option maxRecDepth 100000",
        "set_option maxHeartbeats 0",
        "",
        "namespace R008.GeneratedProofs",
        "",
        "noncomputable section",
        "",
    ]

    global_names: list[str] = []
    for certificate in DOC["certificates"]:
        cname = ident(certificate["name"])
        degree = certificate["degree"]
        n = degree + 1
        sign = certificate["requiredSign"]
        coeffs = [q(x) for x in certificate["powerCoefficientsAscending"]]
        polynomial_name = f"{cname}Polynomial"
        lines.extend([
            f"def {polynomial_name} (t : ℝ) : ℝ :=",
            f"  {polynomial_expr(coeffs)}",
            "",
        ])
        piece_interval_names: list[str] = []
        piece_rights: list[Q] = []
        original_left = q(certificate["originalInterval"]["left"])
        original_right = q(certificate["originalInterval"]["right"])

        for index, piece in enumerate(certificate["pieces"]):
            stem = f"{cname}Piece{index:02d}"
            beta = [q(x) for x in piece["bernsteinCoefficients"]]
            left = q(piece["left"])
            right = q(piece["right"])
            margin = q(piece["strictMargin"])
            beta_name = f"{stem}Beta"
            margin_name = f"{stem}Margin"
            identity_name = f"{stem}Identity"
            bound_name = f"{stem}CoefficientBound"
            unit_name = f"{stem}OnUnit"
            interval_name = f"{stem}OnInterval"
            piece_interval_names.append(interval_name)
            piece_rights.append(right)

            lines.extend([
                f"def {beta_name} : Fin {n} → ℝ :=",
                f"  {vector_expr(beta)}",
                "",
                f"def {margin_name} : ℝ := {lean_r(margin)}",
                "",
                f"theorem {identity_name} (x : Set.Icc (0 : ℝ) 1) :",
                f"    {polynomial_name} ({lean_r(left)} +",
                f"      ({lean_r(right)} - {lean_r(left)}) * (x : ℝ)) =",
                f"      R008.weightedBernstein {beta_name} x := by",
                f"  norm_num [{polynomial_name}, R008.weightedBernstein, {beta_name},",
                "    bernstein_apply, Fin.sum_univ_succ, Nat.choose] <;> ring_nf",
                "",
            ])
            if sign == "negative":
                lines.extend([
                    f"theorem {bound_name} :",
                    f"    ∀ k, {beta_name} k ≤ {margin_name} := by",
                    "  intro k",
                    f"  fin_cases k <;> norm_num [{beta_name}, {margin_name}]",
                    "",
                    f"theorem {unit_name} (x : Set.Icc (0 : ℝ) 1) :",
                    f"    {polynomial_name} ({lean_r(left)} +",
                    f"      ({lean_r(right)} - {lean_r(left)}) * (x : ℝ)) < 0 := by",
                    f"  rw [{identity_name}]",
                    f"  exact R008.weightedBernstein_strictly_negative",
                    f"    {beta_name} {margin_name} x {bound_name}",
                    f"    (by norm_num [{margin_name}])",
                    "",
                ])
            else:
                lines.extend([
                    f"theorem {bound_name} :",
                    f"    ∀ k, {margin_name} ≤ {beta_name} k := by",
                    "  intro k",
                    f"  fin_cases k <;> norm_num [{beta_name}, {margin_name}]",
                    "",
                    f"theorem {unit_name} (x : Set.Icc (0 : ℝ) 1) :",
                    f"    0 < {polynomial_name} ({lean_r(left)} +",
                    f"      ({lean_r(right)} - {lean_r(left)}) * (x : ℝ)) := by",
                    f"  rw [{identity_name}]",
                    f"  exact R008.weightedBernstein_strictly_positive",
                    f"    {beta_name} {margin_name} x {bound_name}",
                    f"    (by norm_num [{margin_name}])",
                    "",
                ])

            result = f"{polynomial_name} t < 0" if sign == "negative" else f"0 < {polynomial_name} t"
            lines.extend([
                f"theorem {interval_name} (t : ℝ)",
                f"    (hLeft : {lean_r(left)} ≤ t) (hRight : t ≤ {lean_r(right)}) :",
                f"    {result} := by",
                f"  have hInterval : {lean_r(left)} < {lean_r(right)} := by norm_num",
                f"  let x : Set.Icc (0 : ℝ) 1 :=",
                f"    ⟨R008.unitCoordinate ({lean_r(left)}) ({lean_r(right)}) t,",
                f"      R008.unitCoordinate_mem hInterval hLeft hRight⟩",
                f"  have h := {unit_name} x",
                f"  have hAffine : {lean_r(left)} +",
                f"      ({lean_r(right)} - {lean_r(left)}) * (x : ℝ) = t := by",
                "    change _ + (_ - _) * R008.unitCoordinate _ _ _ = _",
                "    exact R008.affine_unitCoordinate hInterval",
                "  rw [hAffine] at h",
                "  exact h",
                "",
            ])

        global_name = f"{cname}Certified"
        global_names.append(global_name)
        result = f"{polynomial_name} t < 0" if sign == "negative" else f"0 < {polynomial_name} t"
        lines.extend([
            f"theorem {global_name} (t : ℝ)",
            f"    (hLeft : {lean_r(original_left)} ≤ t)",
            f"    (hRight : t ≤ {lean_r(original_right)}) :",
            f"    {result} := by",
        ])
        indent = "  "
        current_left_expr = "hLeft"
        for index, interval_name in enumerate(piece_interval_names):
            right = piece_rights[index]
            if index + 1 < len(piece_interval_names):
                hname = f"h{index}"
                lines.append(f"{indent}by_cases {hname} : t ≤ {lean_r(right)}")
                lines.append(f"{indent}· exact {interval_name} t {current_left_expr} {hname}")
                lines.append(f"{indent}· have hLower{index + 1} : {lean_r(right)} ≤ t :=")
                lines.append(f"{indent}    le_of_lt (lt_of_not_ge {hname})")
                current_left_expr = f"hLower{index + 1}"
                indent += "  "
            else:
                lines.append(f"{indent}exact {interval_name} t {current_left_expr} hRight")
        lines.append("")

    lines.extend([
        "/-- All five exact sign obligations needed by the R008 manuscript,",
        "expressed directly in terms of the generated power-basis functions. -/",
        "structure AllR008IntervalSigns : Prop where",
        "  strongNonfar : ∀ t, (-(442 : ℝ) / 625) ≤ t → t ≤ 1 / 2 →",
        "    strongNonfarNegativePolynomial t < 0",
        "  strongFar : ∀ t, -1 ≤ t → t ≤ (-(442 : ℝ) / 625) →",
        "    0 < strongFarBelowOnePolynomial t",
        "  moderateNonfar : ∀ t, (-(133 : ℝ) / 200) ≤ t → t ≤ 1 / 2 →",
        "    moderateNonfarNegativePolynomial t < 0",
        "  moderateFar : ∀ t, -1 ≤ t → t ≤ (-(133 : ℝ) / 200) →",
        "    0 < moderateFarBelowOnePolynomial t",
        "  local : ∀ t, -1 ≤ t → t ≤ (2311 : ℝ) / 22311 →",
        "    localNegativePolynomial t < 0",
        "",
        "theorem allR008IntervalSigns : AllR008IntervalSigns := {",
        "  strongNonfar := strongNonfarNegativeCertified",
        "  strongFar := strongFarBelowOneCertified",
        "  moderateNonfar := moderateNonfarNegativeCertified",
        "  moderateFar := moderateFarBelowOneCertified",
        "  local := localNegativeCertified",
        "}",
        "",
        "end R008.GeneratedProofs",
        "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(generate(), encoding="utf-8")
    print(f"generated {OUT}")
